## @(#) : textlint prh dictionary
#
# @version 1.0.0
# @author  Furukawa, Atsushi <atsushifx@gmail.com>
# @date    2025-01-31
# @license MIT
#
# @desc<<
#
# textlint prh base dictionary
#
#<<

version: 1
#
imports:
  ## smarthr proofreading dictionary
  ## atsushifx's add-on
